apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter
        ports:
        - containerPort: 9116
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  ports:
  - port: 9116
    targetPort: 9116
  selector:
    app: snmp-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: snmp-exporter
  endpoints:
  - port: 9116
    path: /snmp
    params:
      module: [if_mib]
    interval: 30s
  namespaceSelector:
    matchNames:
    - monitoring
