apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
      - name: speedtest-exporter
        image: ghcr.io/miguelndecarvalho/speedtest-exporter:latest
        ports:
        - containerPort: 9798
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  ports:
  - port: 9798
    targetPort: 9798
  selector:
    app: speedtest-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: speedtest-exporter
  endpoints:
  - port: 9798
    interval: 30m
