apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus-blackbox-exporter
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: blackbox-exporter
  namespace: monitoring
